force-app/main/default/objects/AtivoCarteira__c/AtivoCarteira__c.object-meta.xml
<CustomObject>
    <description>Ativos de uma determinada carteira</description>
    <label>Ativo de Carteira</label>
    <nameField>
        <displayFormat>ATC-{000000}</displayFormat>
        <label>Codigo de Ativo de Carteira</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos de Carteira</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Ordem de compra ou venda de ativos</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD{000000}</displayFormat>
        <label>Código de Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordem__c/fields/AtivoCarteira__c.field-meta.xml
<CustomField>
    <fullName>AtivoCarteira__c</fullName>
    <label>Ativo de Carteira</label>
    <referenceTo>AtivoCarteira__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Executada</fullName>
                <default>true</default>
                <label>Não Executada</label>
            </value>
            <value>
                <fullName>Em Processamento</fullName>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada pelo Usuário</fullName>
            </value>
            <value>
                <fullName>Cancelada por falta de saldo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ordem__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compra</fullName>
            </value>
            <value>
                <fullName>Venda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrdemTriggerHandler.cls
public with sharing class OrdemTriggerHandler extends TriggerHandler { 
    
	protected override void beforeInsert(){
          System.debug('Before Insert' );
          Set<Id>SetIdAtvc= new Set<Id>();
          Map<Id,AtivoCarteiraModel> mapAtivoCarteiraModel = new Map<Id,AtivoCarteiraModel>();          
          
          //Define os IDs de Ativos de carteira para montar a query para recuperar dados dos ativos de carteira
          for(Ordem__c o: (List<Ordem__c>) trigger.new){
               SetIdAtvc.add(o.Ativocarteira__c) ;     
          }
          System.debug('Size SetId = ' + SetIdAtvc.size() );
          //Cria um mapa de modelo de ativo de carteira com dados recuparados do banco
          mapAtivoCarteiraModel = AtivoCarteiraModel.getMapFromDataBank(SetIdAtvc);
          
          //Implementa as regas de negócio para as ordens
          for (Ordem__c o : (List<Ordem__c>) trigger.new){
             System.debug(o.Tipo__c);
             if(o.Status__c == 'Executada'){
               AtivoCarteiraModel atvm = mapAtivoCarteiraModel.get(o.AtivoCarteira__c);
               if(o.Tipo__c == 'Compra'){
                   //Para teste
                    OrdemHandler.handlerCompra(o,atvm );
               }
               else if (o.Tipo__c == 'Venda'){
                    //Para teste
                    OrdemHandler.handlerVenda(o,atvm );
               }
               //Salva as alterações no modelo de ativo de carteira no mapa
               if (atvm != null){  
                    mapAtivoCarteiraModel.put(atvm.Id,atvm) ;
               } 
             }             
          } 
          
      }
     
     
    
}