force-app/main/default/objects/AtivoCarteira__c/AtivoCarteira__c.object-meta.xml
<CustomObject>
    <description>Ativos de uma determinada carteira</description>
    <label>Ativo de Carteira</label>
    <nameField>
        <displayFormat>ATC-{000000}</displayFormat>
        <label>Codigo de Ativo de Carteira</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos de Carteira</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AtivoCarteira__c/fields/PrecoMedio__c.field-meta.xml
<CustomField>
    <fullName>PrecoMedio__c</fullName>
    <description>Preço médio persistido do ativo de carteira</description>
    <label>Preço Médio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AtivoCarteira__c/fields/PrecoMedioCalculado__c.field-meta.xml
<CustomField>
    <fullName>PrecoMedioCalculado__c</fullName>
    <description>Preço Médio de Compra</description>
    <formula>ValorInvestidoCalculado__c /  QuantidadeCalculada__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Preço Médio de Compra</inlineHelpText>
    <label>Preço Médio Calculado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AtivoCarteira__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade usada para calcular o preço médio</description>
    <inlineHelpText>Quantidade usada para calcular o preço médio</inlineHelpText>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AtivoCarteira__c/fields/QuantidadeCalculada__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeCalculada__c</fullName>
    <description>Quantidade de um determinado ativo na carteira</description>
    <label>Quantidade Calculada</label>
    <summarizedField>Ordem__c.QuantidadeContabil__c</summarizedField>
    <summaryFilterItems>
        <field>Ordem__c.Status__c</field>
        <operation>equals</operation>
        <value>Executada</value>
    </summaryFilterItems>
    <summaryForeignKey>Ordem__c.AtivoCarteira__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AtivoCarteira__c/fields/ValorInvestido__c.field-meta.xml
<CustomField>
    <fullName>ValorInvestido__c</fullName>
    <description>Valor Total Investido na compra do ativo</description>
    <label>Valor Investido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Ordem de compra ou venda de ativos</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD{000000}</displayFormat>
        <label>Código de Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordem__c/fields/AtivoCarteira__c.field-meta.xml
<CustomField>
    <fullName>AtivoCarteira__c</fullName>
    <label>Ativo de Carteira</label>
    <referenceTo>AtivoCarteira__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ordem__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <description>Preço unitário dos ativos a serem negociados</description>
    <inlineHelpText>Preço unitário dos ativos a serem negociados</inlineHelpText>
    <label>Preço</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ordem__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de ativos a serem negociados</description>
    <inlineHelpText>Quantidade de ativos a serem negociados</inlineHelpText>
    <label>Quantidade</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Executada</fullName>
                <default>true</default>
                <label>Não Executada</label>
            </value>
            <value>
                <fullName>Em Processamento</fullName>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada pelo Usuário</fullName>
            </value>
            <value>
                <fullName>Cancelada por falta de saldo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ordem__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compra</fullName>
            </value>
            <value>
                <fullName>Venda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AtivoCarteiraHandler.cls
public class AtivoCarteiraHandler {  
    
    /*
     //Calcular o custo Total de compra do Ativo de Carteira
    public static AtivoCarteira__c calculaCustoTotal(Ordem__c ordem, AtivoCarteira__c atc){
        //AtivoCarteira__c atcSaida = new AtivoCarteira__c();
        Double quant = 0 ;   
        Double valorInvestido = 0 ;	
        
        //Soma o valor de ordem de compra ao valor total do ativo de carteira
        if(ordem.Tipo__c == 'Compra'){
          quant = atc.Quantidade__c + ordem.Quantidade__c;     
          valorInvestido =  atc.ValorInvestido__c + ordem.Quantidade__c * ordem.Preco__c;
          atc.PrecoMedio__c =  valorInvestido / quant;
			
        }
        
        //Debita quantidade  e o valor total  de ordem de venda na carteira
        else if (ordem.Tipo__c == 'Venda'){
            quant = atc.Quantidade__c - ordem.Quantidade__c;  
            valorInvestido =  atc.PrecoMedio__c * quant;
        }
        atc.Quantidade__c = quant;
        atc.ValorInvestido__c = valorInvestido;
        return atc;
    } 
    
   
    
    public static List<AtivoCarteira__c> calculaPrecoMedioCompra(List<Ordem__c> ordens){
        Map<Id,AtivoCarteira__c> mapAtivoCarteiras = new Map<Id,AtivoCarteira__c>();
        List<AtivoCarteira__c>ativosCarteiras = new List<AtivoCarteira__c>();
        
        for(Ordem__c o:ordens){
             AtivoCarteira__c atc = new AtivoCarteira__c();            
             if(o.Status__c == 'Executada'){
				//Se o ativo de carteira não for encontrado no mapa é usado são usados os valores do banco como referência;				         
            	if (mapAtivoCarteiras.get(o.AtivoCarteira__r.Id) == null){
                    atc = o.AtivoCarteira__r;
                    atc.Quantidade__c = atc.QuantidadeCalculada__c;
                    atc.PrecoMedio__c = atc.PrecoMedioCalculado__c;
                } 
                 
               	//Se o ativo de carteira  for encontrado no mapa é realizado o cálculo com o mesmo e a ordem de entrada 	
            	else{
                	atc = mapAtivoCarteiras.get(o.AtivoCarteira__r.Id);
            	}                 
                // Calcula os valores de quantidade e preço médio de compra dos ativos de carteira e salva no Mapa
            	mapAtivoCarteiras.put(atc.Id,calculaCustoTotal(o,atc));
             }               
        }
        
        for(AtivoCarteira__c ac: mapAtivoCarteiras.values()){
            ativosCarteiras.add(ac);
        }
        return ativosCarteiras;
    }
     */
    
    
    
    
}