force-app/main/default/objects/AtivoCarteira__c/AtivoCarteira__c.object-meta.xml
<CustomObject>
    <description>Ativos de uma determinada carteira</description>
    <label>Ativo de Carteira</label>
    <nameField>
        <displayFormat>ATC-{000000}</displayFormat>
        <label>Codigo de Ativo de Carteira</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos de Carteira</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AtivoCarteira__c/fields/CarteiraInvestimentos__c.field-meta.xml
<CustomField>
    <fullName>CarteiraInvestimentos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relação entre Carteira e Ativos de Carteira</description>
    <inlineHelpText>Relação entre Carteira e Ativos de Carteira</inlineHelpText>
    <label>Carteira de Investimentos</label>
    <referenceTo>CarteiraInvestimentos__c</referenceTo>
    <relationshipLabel>Ativos de Carteira</relationshipLabel>
    <relationshipName>AtivosCarteira</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AtivoCarteira__c/fields/QuantidadeCalculada__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeCalculada__c</fullName>
    <description>Quantidade de um determinado ativo na carteira</description>
    <label>Quantidade Calculada</label>
    <summarizedField>Ordem__c.QuantidadeContabil__c</summarizedField>
    <summaryFilterItems>
        <field>Ordem__c.Status__c</field>
        <operation>equals</operation>
        <value>Executada</value>
    </summaryFilterItems>
    <summaryForeignKey>Ordem__c.AtivoCarteira__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AtivoCarteira__c/fields/ValorInvestidoCalculado__c.field-meta.xml
<CustomField>
    <fullName>ValorInvestidoCalculado__c</fullName>
    <description>Calcula o valor total investido do ativo na carteira</description>
    <inlineHelpText>Calcula o valor total investido do ativo na carteira</inlineHelpText>
    <label>Valor Investido Calculado</label>
    <summarizedField>Ordem__c.ValorTotalContabil__c</summarizedField>
    <summaryForeignKey>Ordem__c.AtivoCarteira__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/CarteiraInvestimentos__c/CarteiraInvestimentos__c.object-meta.xml
<CustomObject>
    <label>Carteira de Investimentos</label>
    <nameField>
        <label>Código da Carteira</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carteiras de Investimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CarteiraInvestimentos__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <description>Saldo em Carteira</description>
    <inlineHelpText>Saldo em Carteira</inlineHelpText>
    <label>Saldo</label>
    <summarizedField>Transacao__c.ValorContabil__c</summarizedField>
    <summaryForeignKey>Transacao__c.CarteiraInvestimentos__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Ordem de compra ou venda de ativos</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD{000000}</displayFormat>
        <label>Código de Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordem__c/fields/AtivoCarteira__c.field-meta.xml
<CustomField>
    <fullName>AtivoCarteira__c</fullName>
    <label>Ativo de Carteira</label>
    <referenceTo>AtivoCarteira__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AtivoCarteiraModel.cls
public class AtivoCarteiraModel {
    public Id Id;
    public double quantidadeAtivo;
    public double totalInvestido;
    public double saldoTotalCarteira;
    
    public AtivoCarteiraModel(){
        
    }
    
    public AtivoCarteiraModel(AtivoCarteira__c at){
        this.Id = at.Id;
        this.quantidadeAtivo = at.QuantidadeCalculada__c;
        this.totalInvestido = at.ValorInvestidoCalculado__c;
        this.saldoTotalCarteira = at.CarteiraInvestimentos__r.Saldo__c;
    }

    public AtivoCarteiraModel(Ordem__c o){
        this.Id = o.AtivoCarteira__c;
        this.quantidadeAtivo = o.AtivoCarteira__r.QuantidadeCalculada__c;
        this.totalInvestido = o.AtivoCarteira__r.ValorInvestidoCalculado__c;
        this.saldoTotalCarteira = o.AtivoCarteira__r.CarteiraInvestimentos__r.Saldo__c;
    } 
    
    public static Map<Id,AtivoCarteiraModel> getMapFromDataBank(Set<Id> SetId){
        Map<Id,AtivoCarteiraModel> mapSaida = new Map<Id,AtivoCarteiraModel>();
        for (AtivoCarteira__c atc : (List<AtivoCarteira__c>)[Select Id , QuantidadeCalculada__c, 
            ValorInvestidoCalculado__c,CarteiraInvestimentos__r.Saldo__c
                from  AtivoCarteira__c where Id in :SetId]){

            AtivoCarteiraModel atcm = new AtivoCarteiraModel(atc);
            System.debug('Total Investido: ' + atcm.Id);
             mapSaida.put(atcm.Id, atcm);
        }
        return mapSaida;
    }
}