force-app/main/default/objects/AtivoCarteira__c/AtivoCarteira__c.object-meta.xml
<CustomObject>
    <description>Ativos de uma determinada carteira</description>
    <label>Ativo de Carteira</label>
    <nameField>
        <displayFormat>ATC-{000000}</displayFormat>
        <label>Codigo de Ativo de Carteira</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos de Carteira</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Ordem de compra ou venda de ativos</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD{000000}</displayFormat>
        <label>Código de Ordem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordem__c/fields/AtivoCarteira__c.field-meta.xml
<CustomField>
    <fullName>AtivoCarteira__c</fullName>
    <label>Ativo de Carteira</label>
    <referenceTo>AtivoCarteira__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrdemHandler.cls
public class OrdemHandler {
    
    public static List<Ordem__c> registraOrdens(List<Ordem__c> ordens){
         List<Ordem__c> ordensSaida = new List<Ordem__c>();
        
        return ordensSaida;
    }
    
    private static Map<Id,AtivoCarteiraModel> getMapAtivoCarteiraModel(){
        Map<Id,AtivoCarteiraModel> mapAtivoCarteiraModel = new Map<Id,AtivoCarteiraModel>();
        
        return mapAtivoCarteiraModel;
        
    }
    
    private static List<AtivoCarteira__c> getAtivoCarteira(Map<Id,AtivoCarteira__c> mapAtc){
       List<AtivoCarteira__c> lista = (List<AtivoCarteira__c>) [Select id from  AtivoCarteira__c where Id in :mapAtc.keySet()];
        return lista;
    }
    
    

}